
server:
  port: 8081


# RocketMq相关配置
rocketmq:
  ###consumer
  publicityProducer:
    ## 该应用是否启用消费者
    isOnOff: on
    groupName: testConsumerGroup
    #mq的nameserver地址
    namesrvAddr: 192.168.152.134:9876;192.168.152.137:9876
    #该消费者订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*;
    topic: testTopic
    tag: tag1
    #rocketmq.consumer.topics=DemoTopic~*;
    consumeThreadMin: 20
    consumeThreadMax: 64
    #设置一次消费消息的条数，默认为1条
    consumeMessageBatchMaxSize: 1

